defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *defaults
  database: uniara_forum_development

test:
  <<: *defaults
  database: uniara_forum_test

production:
  <<: *defaults
  database: uniara_forum_production
